# Generated by Django 3.0.14 on 2022-05-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numbers', models.CharField(max_length=200)),
                ('Results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Results')),
            ],
        ),
    ]
