# Generated by Django 3.0.14 on 2022-05-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='results',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
    ]
